name: Split.io CLI - DockerHub Image

on:
  workflow_dispatch:
    inputs:
      flag_name:
        description: 'Feature flag name to update'
        required: true
        default: 'test_flag'
      treatment:
        description: 'Treatment to set'
        required: true
        default: "on"
        type: choice
        options:
          - "on"
          - "off"
      workspace_id:
        description: 'Split.io workspace ID'
        required: true
        default: '0210c6e0-45f6-11ef-b5c3-96efbcda2157'
      environment_id:
        description: 'Split.io environment ID'
        required: true
        default: '3dcfbab0-45f6-11ef-a919-d2230ba6d777'

jobs:
  run-splitio-command:
    runs-on: ubuntu-latest
    container:
      image: sponmuth/split
      env:
        SPLITIO_API_KEY: ${{ secrets.SPLITIO_API_KEY }}
      ports:
        - 80
    steps:
      - name: Run Split.io CLI command
        run: --help
