name: Terraform Plan and Apply

on:
  workflow_call:
    inputs:
      terraform-version:
        description: 'Terraform version to use'
        required: false
        type: string
        default: '1.5.0'
      terraform-directory:
        description: 'Directory containing Terraform files'
        required: false
        type: string
        default: '.'
      auto-approve:
        description: 'Auto-approve terraform apply (skip approval)'
        required: false
        type: boolean
        default: false
      plan-only:
        description: 'Only run terraform plan, skip apply'
        required: false
        type: boolean
        default: false

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.plan.outputs.has-changes }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        
    - name: Terraform Init
      working-directory: ${{ inputs.terraform-directory }}
      run: terraform init
        
    - name: Terraform Plan
      id: plan
      working-directory: ${{ inputs.terraform-directory }}
      run: |
        terraform plan -out=tfplan
        
        # Check if plan has changes
        if terraform show tfplan | grep -q "No changes"; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected."
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected."
        fi
        
        # Save plan summary
        terraform show tfplan > plan-summary.txt
        
    - name: Debug Outputs
      run: |
        echo "=== DEBUG OUTPUTS ==="
        echo "plan-only: ${{ inputs.plan-only }}"
        echo "auto-approve: ${{ inputs.auto_approve }}"
        echo "has_changes: ${{ steps.plan.outputs.has_changes }}"
        echo "====================="
        
    - name: Upload Plan Files
      uses: actions/upload-artifact@v4
      with:
        name: terraform-files
        path: |
          ${{ inputs.terraform-directory }}/tfplan
          ${{ inputs.terraform-directory }}/plan-summary.txt

  terraform-approval:
    name: Wait for Approval
    needs: terraform-plan
    if: ${{ inputs.plan-only == false && inputs.auto_approve == false }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Debug Approval Job
      run: |
        echo "=== APPROVAL JOB DEBUG ==="
        echo "plan-only: ${{ inputs.plan-only }}"
        echo "auto-approve: ${{ inputs.auto_approve }}"
        echo "has_changes: ${{ needs.terraform-plan.outputs.has_changes }}"
        echo "=========================="
        
    - name: Download Plan Files
      uses: actions/download-artifact@v4
      with:
        name: terraform-files
        path: ${{ inputs.terraform-directory }}
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        
    - name: Show Plan Summary
      working-directory: ${{ inputs.terraform-directory }}
      run: |
        echo "=== TERRAFORM PLAN SUMMARY ==="
        cat plan-summary.txt
        echo ""
        echo "=== APPROVAL REQUIRED ==="
        echo "Please approve this deployment using the manual approval step below."
        
    - name: Manual Approval
      uses: trstringer/manual-approval@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        approvers: ${{ github.actor }}
        minimum-approvals: 1
        issue-title: "🚀 Terraform Approval Required - ${{ github.ref_name }}"
        issue-body: |
          ## Terraform Changes Ready to Apply
          
          **Branch:** ${{ github.ref_name }}
          **Directory:** ${{ inputs.terraform-directory }}
          **Workflow Run:** ${{ github.run_id }}
          
          ### Plan Summary
          The Terraform plan has been generated and requires approval before applying changes.
          
          ### To Approve
          Please review the plan above and approve this deployment if the changes are correct.
          
          ### Changes Detected
          - Resources to add/modify/delete
          - Plan file: Available in workflow artifacts
          - Plan summary: Available in workflow artifacts
          
          **⚠️ Warning:** This will apply infrastructure changes to your environment.

  terraform-apply:
    name: Terraform Apply
    needs: [terraform-plan, terraform-approval]
    if: ${{ inputs.plan-only == false && (inputs.auto_approve == true || needs.terraform-plan.outputs.has_changes == 'false') }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download Plan Files
      uses: actions/download-artifact@v4
      with:
        name: terraform-files
        path: ${{ inputs.terraform-directory }}
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        
    - name: Terraform Init
      working-directory: ${{ inputs.terraform-directory }}
      run: terraform init
        
    - name: Terraform Apply
      working-directory: ${{ inputs.terraform-directory }}
      run: |
        echo "Applying Terraform plan..."
        terraform apply tfplan
        echo "✅ Terraform apply completed!"
        
    - name: Show Results
      working-directory: ${{ inputs.terraform-directory }}
      run: |
        echo "=== APPLY RESULTS ==="
        terraform show
