name: Test Terraform Approval

on:
  workflow_dispatch:
    inputs:
      auto_approve:
        description: 'Auto-approve changes (skip approval)'
        required: false
        type: string
        default: 'false'
      plan_only:
        description: 'Only run terraform plan, skip apply'
        required: false
        type: string
        default: 'false'

# jobs:
#   test-terraform:
#     uses: ./.github/workflows/terraform-plan-apply.yml
#     with:
#       terraform-directory: './terraform'
#       auto-approve: ${{ github.event.inputs.auto_approve == 'true' }}
#       plan-only: ${{ github.event.inputs.plan_only == 'true' }}


jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: user1,user2,org-team1
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          issue-body-file-path: relative/file_path/wrt/repo/root
          exclude-workflow-initiator-as-approver: false
          fail-on-denial: true
          additional-approved-words: ''
          additional-denied-words: ''

  follow-up-job:
    needs: approve
    runs-on: ubuntu-latest
    if: ${{ always() && !failure() && !cancelled() }}
    steps:
      - run: echo "Running follow-up task"

