name: Test Terraform Approval

on:
  workflow_dispatch:
    inputs:
      auto_approve:
        description: 'Auto-approve changes (skip approval)'
        required: false
        type: string
        default: 'false'
      plan_only:
        description: 'Only run terraform plan, skip apply'
        required: false
        type: string
        default: 'false'

permissions:
  contents: read
  issues: write
  actions: read

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1.11.0
        with:
          secret: ${{ github.TOKEN }}
          timeout-minutes: 1
          approvers: sprasantinsulet

  follow-up-job:
    needs: approve
    runs-on: ubuntu-latest
    if: ${{ always() && !failure() && !cancelled() }}
    steps:
      - run: echo "Running follow-up task"

